# Generated by Django 5.1.7 on 2025-09-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=255)),
                ('from_city_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('to_city', models.CharField(max_length=255)),
                ('to_city_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('travel_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20)),
                ('travel_class_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('label_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('location_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('wifi', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('prayer_room', models.BooleanField(default=False)),
                ('beach_access', models.BooleanField(default=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('links', models.ManyToManyField(blank=True, to='ttry.link')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('banner', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('content_ar', models.TextField(blank=True, null=True)),
                ('links', models.ManyToManyField(blank=True, to='ttry.link')),
            ],
        ),
        migrations.CreateModel(
            name='HajjOmrah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('package_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('links', models.ManyToManyField(blank=True, to='ttry.link')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('message_ar', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('links', models.ManyToManyField(blank=True, to='ttry.link')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField()),
                ('requirements_ar', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('links', models.ManyToManyField(blank=True, to='ttry.link')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('content_ar', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('links', models.ManyToManyField(blank=True, to='ttry.link')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('links', models.ManyToManyField(blank=True, to='ttry.link')),
            ],
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('links', models.ManyToManyField(blank=True, to='ttry.link')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_location_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('cartype', models.CharField(max_length=255)),
                ('cartype_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('priceperday', models.CharField(max_length=300)),
                ('priceperday_ar', models.CharField(blank=True, max_length=300, null=True)),
                ('pricepermonth', models.CharField(max_length=300)),
                ('pricepermonth_ar', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('links', models.ManyToManyField(blank=True, to='ttry.link')),
            ],
        ),
        migrations.CreateModel(
            name='Travelpackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('product_name_ar', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('image', models.CharField(max_length=450)),
                ('links', models.ManyToManyField(blank=True, to='ttry.link')),
            ],
        ),
        migrations.CreateModel(
            name='TravelTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('destination_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('links', models.ManyToManyField(blank=True, to='ttry.link')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('links', models.ManyToManyField(blank=True, to='ttry.link')),
            ],
        ),
    ]
